#! /bin/sh
# kcminputrc Mouse cursorTheme 'menda_cursors'
kcminputrc_mouse_cursortheme=menda_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Menda
ksplashrc_ksplash_theme=org.kde.menda.desktop
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
